[package]
name = "vcflevel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

vcf = "0.6.0"
flate2 = "1.0.22"
clap = "2.33.3"